### ISSUE TITLE
Maximum payload size

### ISSUE THREAD

**Issue by irohiroki** [tompesman/push-apns#10]
[APNs document says it accepts 4KB of payload](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1) but [BinaryNotificationValidator limits it to 256 bytes](https://github.com/tompesman/push-apns/blob/f77090da1f8f2d57a08212174d6b0202b8854d96/lib/push/apns/binary_notification_validator.rb#L6). I think it should be 4096. Or am I missing something?

**Comment by tompesman** [comment]
That's true, but this gem uses the legacy APNS API. I think you should use https://github.com/9to5/pushr-core with https://github.com/9to5/pushr-apns2

**Comment by irohiroki** [comment]
Thanks.
