### ISSUE TITLE
content_available accessor not available in Rails 4.

### ISSUE THREAD

**Issue by jim0020** [tompesman/push-apns#7]
Using Rails 4.0.2 with Ruby 2.12p95.  I'm trying to include the content_available attribute in my push message, Everything works fine when I don't include content_available.  When I include content_available : 

Error = unknown attribute: content_available

Here's a snippet : 

            apns_msg = {
              app: 'FEMA',
              device: device.push_token,
              alert: headline,
              sound: 'default',
              badge: device.local_alerts.count + 1,
              content_available: 1, # use this if you want the iOS app to auto launch upon receiving this notification
              attributes_for_device: { identifier: alert.identifier }
            }
            apns_msg[ :expiry ] = time_to_live if ( time_to_live.present? )
            Push::MessageApns.create( apns_msg )

Maybe it's because of the check in message_apns.rb for ActiveModel::MassAssignmentSecurity?  Didn't that go away in Rails 4?

    attr_accessible :app, :device, :alert, :badge, :sound, :expiry, :attributes_for_device, :content_available if defined?(ActiveModel::MassAssignmentSecurity)

**Comment by tompesman** [comment]
released version 1.0.4
